receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  elasticsearch/logs:
    endpoints: [ "http://elasticsearch:9200" ]
    user: "elastic"
    password: "elastic"
    index: "otel-logs-%{+yyyy.MM.dd}"

  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

processors:
  batch: {}

service:
  pipelines:
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ elasticsearch/logs ]

    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp/jaeger ]
