receivers:
  otlp:
    protocols:
      grpc: { }
      http: { }

exporters:
#  jaeger:
#    endpoint: "http://jaeger:14250"
#    tls:
#      insecure: true

  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    logs_index: "otel-logs"       # optional
    tls:
      insecure: true

  logging:
    loglevel: debug

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging ]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ elasticsearch, logging ]

