server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.database}?sslmode=allow
  rabbitmq:
    logging:
      level:
        org.springframework.amqp.rabbit.core.RabbitAdmin: DEBUG

# override prod configurations
postgres:
  host: ${PG_HOST:localhost}
  port: 5432
  database: ${POSTGRES_DB:booking_db}
  username: ${POSTGRES_USER:postgres}
  password: ${POSTGRES_PASSWORD:123}
  disables_autocommit: false

elasticsearch:
  uris: http://${ELASTIC_HOST:localhost}:9200
  username: ${ELASTIC_USER:elastic}
  password: ${ELASTIC_PASSWORD:elastic}

rabbitmq:
  username: ${RABBITMQ_DEFAULT_USER:rabbit_booking_user}
  password: ${RABBITMQ_DEFAULT_PASS:123}

kafka:
  bootstrap-servers: http://${KAFKA_HOST:localhost}:9200

opentelemetry:
  metrics:
    url: http://${OTLP_HOST:localhost}:4318/v1/metrics
  tracing:
    endpoint: http://${OTLP_HOST:localhost}:4318/v1/traces
