server:
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never
  port: ${APP_PORT:8080}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

postgres:
  url: ${DB_URL}
  database: ${DB_NAME}
  username: ${DB_USER}
  password: ${DB_PASSWORD}

elasticsearch:
  uris: ${ELASTICSEARCH_URIS}
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}